### ISSUE TITLE
Empty workflows

### ISSUE THREAD

**Issue by tuvelofstrom** [PacktPublishing/Codeless-Deep-Learning-with-KNIME#1]
All of the projects seem to be entirely empty, without any workflows...

**Comment by Kathrin-Me** [comment]
Hi, 
I just double checked and I can see a .knar file in each folder. 
To inspect the example workflows you need to download the .knar files and import them into KNIME Analytics Platform. 
Cheers
Kathrin

**Comment by nithikpackt** [comment]
Hi @tuvelofstrom ,
The problems seems to be an issue due to LFS on github. So I"ll suggest using Github Desktop software to clone the repo rather than downloading the zip.

Thank you @Kathrin-Me for replying to the issue.
